### ISSUE TITLE
Support using the same port for Spring MVC and gRPC

### ISSUE THREAD

**Issue by making** [spring-projects-experimental/spring-grpc#18]
In some environments, such as PaaS or Knative, using multiple ports may not be the default.
It would be very convenient to be able to serve plain Spring MVC and gRCP on 8080.

I don't know what it uses internally, but Armeria has made it possible.
https://armeria.dev/docs/advanced-spring-boot-integration

**Comment by dsyer** [comment]
See also existing implementation in https://github.com/grpc/grpc-java/tree/master/servlet (link from #14). We can copy that if it works. Not sure if it needs to be a separate jar or not.

**Comment by dsyer** [comment]
I added a sample here: https://github.com/dsyer/spring-grpc/tree/tomcat. There's not much to do, but we'll need a way to selectively disable the autoconfiguration for the netty server. Maybe if the `ApplicationContext` can be recognized as a web application?
