### ISSUE TITLE
Support for tracing

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-grpc#2]
E.g add `GrpcServerTracingAutoConfiguration`.

**Comment by CyberZujo** [comment]
Would like to take this one.

**Comment by dsyer** [comment]
No worries. It might help if you have the interceptors feature already available (cc @onobc )?

**Comment by onobc** [comment]
I will try to get to it soon @dsyer . @CyberZujo also picked up https://github.com/spring-projects-experimental/spring-grpc/issues/26 so hopefully that buys me a bit of time.

**Comment by making** [comment]
I was also playing around with the Tracing support, and I found that　https://github.com/spring-projects-experimental/spring-grpc/pull/42 was required to add `ObservationGrpcServerInterceptor` to `GrpcServlet`.

**Comment by making** [comment]
I'm trying out manual configuration of grpc tracing (via `ObservationGrpcServerInterceptor`/`ObservationGrpcClientInterceptor`), and so far it's working fine.
https://github.com/making/hello-grpc

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/27fbb2c2-a867-4993-8b1d-79e923e84496">

**Comment by dsyer** [comment]
Do we still need some autoconfiguration or is it covered by #1?

**Comment by onobc** [comment]
I believe this is covered by #17 but we should verify this by adding a sample and updating docs to tell users how to turn on tracing for say "Otel + Zipkin" (or whatever example we use). 

<sub>Background [here](https://github.com/spring-projects-experimental/spring-grpc/pull/41#pullrequestreview-2414414584)</sub>

**Comment by dsyer** [comment]
See b16ec9c which adds support for global interceptors to the `GrpcServlet` and metrics to the Tomcat sample. I'll add some docs too.

**Comment by making** [comment]
my example became much simpler 👍
https://github.com/making/hello-grpc/commit/99b5286721a6ee8d432f914ab66fb7abf286698c
