### ISSUE TITLE
Change pom name from "bom" to "dependencies"

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-grpc#28]
We use it to manage `io.grpc` and `io.netty` dependencies, so it's not just a bom. This is consistent with the naming of `spring-boot-dependencies`.

**Comment by varunu28** [comment]
@dsyer Can I give an attempt on this issue?

**Comment by varunu28** [comment]
@dsyer Just to confirm that this task is limited to renaming the pom from `bom -> dependencies` only & not renaming the complete maven artifact? The `artifactId` still remains as `spring-grpc-bom` Correct?

**Comment by dsyer** [comment]
Not sure what you mean. The only thing you can change is the artifact id isn’t it? I suppose we also need to rename the directory.

**Comment by varunu28** [comment]
Thanks for clarifying. I have created https://github.com/spring-projects-experimental/spring-grpc/pull/32 to address this issue.

**Comment by dsyer** [comment]
Fixed in #32
