### ISSUE TITLE
Consolidate quick start docs

### ISSUE THREAD

**Issue by onobc** [spring-projects-experimental/spring-grpc#35]
Currently the README.adoc has more info around quick-start than the ref docs. Let's put this info in a single place in the ref docs and point to the ref docs from the README.

**Comment by dsyer** [comment]
I like having it in both. The README is easier to find for most people, especially if they aren't super familiar with Spring. In Spring Cloud the README is .adoc and autocgenerated. I don't know if it's worth it, and it makes it harder to get people to contribute changes to the README. The alternative is just to live with the duplication. It won't kill us.

**Comment by onobc** [comment]
The content in both places would be nice and its easy to do. Not a high priority though but at the very least they need to be in sync and the README is ahead of the ref doc at this point.

**Comment by dsyer** [comment]
I pushed my `readme` branch onto main. So now they are in sync but not automatically up to date. The docs README has instructions on how to synchronize changes.
