### ISSUE TITLE
Support for ClientInterceptor

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-grpc#52]
Same as for the server side, but possibly complicated by the design of the channel factory.

**Comment by vuhp** [comment]
I would like to take this task. Can you assign it to me?

**Comment by onobc** [comment]
Hi @vuhp , just touching base on this issue. We wanted to get this in for the upcoming release and I was going to grab this one if you had not had a chance to work on it yet. No worries if you have not had time - I know we all get busy. There are also plenty of other issues to grab. 

Thanks,
Chris
