### ISSUE TITLE
Exception Mapping

### ISSUE THREAD

**Issue by benallard** [spring-projects-experimental/spring-grpc#62]
I would like a way to be able to universally map my exceptions to StatusRuntimeException.

like the [GrpcExceptionHandler ](https://github.com/grpc-ecosystem/grpc-spring/blob/master/docs/en/server/exception-handling.md) of the other starters.

**Comment by dsyer** [comment]
Made a start with a global interceptor: 3feca42. I don't like the annotation-first approach, but there may be some annotations later.
