### ISSUE TITLE
Support for in-process transport for testing

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-grpc#7]
Probably only for testing, so best in spring-grpc-test.

**Comment by andreilisa** [comment]
@dsyer, What about having here an annotation ? for instance this one will manage the `InProcessServerBuilder` and `InProcessChannelBuilder` lifecycle ?

**Comment by dsyer** [comment]
I was thinking it would just be the default if the test jar was on the classpath, and there would be a configuration flag to change the default. I’m not sure what your annotation would do.

**Comment by andreilisa** [comment]
The annotation will be used to mark the test classes requiring an in-process gRPC setup. In case with the default one it will fit better.

**Comment by dsyer** [comment]
I see what you mean about a test annotation. We could leave that for a separate decision later, once the basic infrastructure is available and configurable.

**Comment by dsyer** [comment]
100%. You don’t even need to ask. Thank you.

**Comment by dsyer** [comment]
Closed by 2df6c37
