### ISSUE TITLE
Manage com.google.protobuf:protoc in spring-grpc-dependencies 

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects-experimental/spring-grpc#79]
Hello,

I think managing the version of `com.google.protobuf:protoc` in `spring-grpc-dependencies` would be helpful. `io.grpc:protoc-gen-grpc-java` is already managed. Then the Gradle snippet for the `protobuf` configuration could omit the dependency versions.

```gradle
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {
                option 'jakarta_omit'
            }
        }
    }
}
```

This gets rid of `dependencyManagement.importedProperties['protobuf-java.version']` and `dependencyManagement.importedProperties['grpc.version']` which are problematic because of https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/193.

**Comment by dsyer** [comment]
Could you translate that to a pull request maybe?

**Comment by mhalbritter** [comment]
Sure.

**Comment by mhalbritter** [comment]
PR here: https://github.com/spring-projects-experimental/spring-grpc/pull/80
