### ISSUE TITLE
Codec support

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-grpc#8]

**Comment by andreilisa** [comment]
Is the idea about having the option to pass a Custom Codec to the Server or Client as a method parameter to the builder?

**Comment by dsyer** [comment]
Possibly. I'm not sure it has anything to do with actual clients or servers. In gRPC Java there are registries (`CompressorRegistry` and `DecompressorRegistry`) which we could call with references to beans of the correct type. Ultimately we might want to be able to control simple cases from configuration files in a Spring Boot app. You can look at the existing community projects for inspiration (e.g. https://github.com/grpc-ecosystem/grpc-spring/blob/master/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/autoconfigure/GrpcCommonCodecAutoConfiguration.java, but I'm not sure we need a special annotation).

**Comment by andreilisa** [comment]
@dsyer, Here is the [PR](https://github.com/spring-projects-experimental/spring-grpc/pull/31)

**Comment by andreilisa** [comment]
@dsyer I think we can close this ticket as well.
